"""initial schema

Revision ID: 5177c878812c
Revises: 
Create Date: 2026-07-14 18:09:28.054834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5177c878812c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=False),
    sa.Column('transcript_url', sa.String(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('quiz_json', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_number')
    )
    op.create_index(op.f('ix_episodes_id'), 'episodes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('azure_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('pre_questionnaire_completed', sa.Boolean(), nullable=True),
    sa.Column('post_questionnaire_completed', sa.Boolean(), nullable=True),
    sa.Column('user_class', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('teacher_code', sa.String(), nullable=True),
    sa.Column('teacher_name', sa.String(), nullable=True),
    sa.Column('current_episode', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('last_reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_count', sa.Integer(), nullable=True),
    sa.Column('midway_reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('delayed_survey_unlocked', sa.Boolean(), nullable=True),
    sa.Column('delayed_survey_completed', sa.Boolean(), nullable=True),
    sa.Column('delayed_unlock_at', sa.DateTime(), nullable=True),
    sa.Column('lock_email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('unlock_email_sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_azure_id'), 'users', ['azure_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('user_episode_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_episode_progress_id'), 'user_episode_progress', ['id'], unique=False)
    op.create_table('user_episode_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('audio_timestamp_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_episode_reactions_id'), 'user_episode_reactions', ['id'], unique=False)
    op.create_table('user_quiz_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_quiz_responses_id'), 'user_quiz_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_quiz_responses_id'), table_name='user_quiz_responses')
    op.drop_table('user_quiz_responses')
    op.drop_index(op.f('ix_user_episode_reactions_id'), table_name='user_episode_reactions')
    op.drop_table('user_episode_reactions')
    op.drop_index(op.f('ix_user_episode_progress_id'), table_name='user_episode_progress')
    op.drop_table('user_episode_progress')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_azure_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_episodes_id'), table_name='episodes')
    op.drop_table('episodes')
    # ### end Alembic commands ###
